# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65vent_list.proto\",\n\nevent_list\x12\x1e\n\neventDatas\x18\x01 \x03(\x0b\x32\n.eventData\"s\n\teventData\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x03\x12\x0f\n\x07keyword\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x62\x06proto3')



_EVENT_LIST = DESCRIPTOR.message_types_by_name['event_list']
_EVENTDATA = DESCRIPTOR.message_types_by_name['eventData']
event_list = _reflection.GeneratedProtocolMessageType('event_list', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_LIST,
  '__module__' : 'event_list_pb2'
  # @@protoc_insertion_point(class_scope:event_list)
  })
_sym_db.RegisterMessage(event_list)

eventData = _reflection.GeneratedProtocolMessageType('eventData', (_message.Message,), {
  'DESCRIPTOR' : _EVENTDATA,
  '__module__' : 'event_list_pb2'
  # @@protoc_insertion_point(class_scope:eventData)
  })
_sym_db.RegisterMessage(eventData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENT_LIST._serialized_start=20
  _EVENT_LIST._serialized_end=64
  _EVENTDATA._serialized_start=66
  _EVENTDATA._serialized_end=181
# @@protoc_insertion_point(module_scope)
