# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_list.proto\"\'\n\x0bsensor_list\x12\x18\n\x07sensors\x18\x01 \x03(\x0b\x32\x07.sensor\"\xa2\x01\n\x06sensor\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x14\n\x0cvalue_double\x18\x02 \x01(\x01\x12\x13\n\x0bvalue_int64\x18\x03 \x01(\x03\x12\x14\n\x0cvalue_string\x18\x04 \x01(\t\x12\x13\n\x0bvalue_bytes\x18\x05 \x01(\x0c\x12\x11\n\tdata_type\x18\x06 \x01(\x03\x12\x0f\n\x07quality\x18\x07 \x01(\x03\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x62\x06proto3')



_SENSOR_LIST = DESCRIPTOR.message_types_by_name['sensor_list']
_SENSOR = DESCRIPTOR.message_types_by_name['sensor']
sensor_list = _reflection.GeneratedProtocolMessageType('sensor_list', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_LIST,
  '__module__' : 'sensor_list_pb2'
  # @@protoc_insertion_point(class_scope:sensor_list)
  })
_sym_db.RegisterMessage(sensor_list)

sensor = _reflection.GeneratedProtocolMessageType('sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'sensor_list_pb2'
  # @@protoc_insertion_point(class_scope:sensor)
  })
_sym_db.RegisterMessage(sensor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSOR_LIST._serialized_start=21
  _SENSOR_LIST._serialized_end=60
  _SENSOR._serialized_start=63
  _SENSOR._serialized_end=225
# @@protoc_insertion_point(module_scope)
